programs:
  - id: program.electrical_engineering
    name: Electrical Engineering
    aliases:
      - EE
      - BSEE
      - Electrical Engineering major
    status: active
    degree_type: Bachelor of Science
    school: School of Engineering and Computing
    accreditation:
      - ABET

  - id: program.computer_engineering
    name: Computer Engineering
    aliases:
      - CPE
      - CPEN
      - BSCPEN
      - Computer Engineering major
    status: active
    degree_type: Bachelor of Science
    school: School of Engineering and Computing
    accreditation:
      - ABET

  - id: program.computer_science
    name: Computer Science
    aliases:
      - CS
      - CPSC
      - Computer Science major
    status: active
    degree_type: Bachelor of Science
    school: School of Engineering and Computing
    accreditation:
      - ABET

  - id: program.information_science
    name: Information Science
    aliases:
      - IS
      - BSIS
      - Information Science major
    status: active
    degree_type: Bachelor of Science
    school: School of Engineering and Computing

  - id: program.cybersecurity
    name: Cybersecurity
    aliases:
      - Cyber
      - CYBR
      - Cybersecurity major
    status: active
    degree_type: Bachelor of Science
    school: School of Engineering and Computing

  - id: program.physics
    name: Physics
    aliases:
      - PHYS
      - Physics major
    status: active
    degree_type: Bachelor of Science
    school: School of Engineering and Computing
